// Mocks generated by Mockito 5.4.6 from annotations
// in bitacora/test/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bitacora/firebase_service.dart' as _i7;
import 'package:bitacora/services/local_cache_service.dart' as _i3;
import 'package:bitacora/subject_model.dart' as _i6;
import 'package:bitacora/task_model.dart' as _i5;
import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCacheService extends _i1.Mock implements _i3.LocalCacheService {
  MockLocalCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> get connectionStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStream),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasConnection, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> cacheTask(_i5.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheTasks(List<_i5.Task>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTasks, [tasks]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i5.Task> getCachedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTasks, []),
            returnValue: <_i5.Task>[],
          )
          as List<_i5.Task>);

  @override
  _i5.Task? getCachedTask(String? taskId) =>
      (super.noSuchMethod(Invocation.method(#getCachedTask, [taskId]))
          as _i5.Task?);

  @override
  _i4.Future<void> removeCachedTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCachedTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheSubject(_i6.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSubject, [subject]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheSubjects(List<_i6.Subject>? subjects) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSubjects, [subjects]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i6.Subject> getCachedSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSubjects, []),
            returnValue: <_i6.Subject>[],
          )
          as List<_i6.Subject>);

  @override
  _i4.Future<void> removeCachedSubject(String? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCachedSubject, [subjectId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markPendingSync(
    String? entityType,
    String? entityId,
    String? operation, {
    String? careerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markPendingSync,
              [entityType, entityId, operation],
              {#careerId: careerId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<Map<String, dynamic>> getPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSync, []),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  _i4.Future<void> clearPendingSync() =>
      (super.noSuchMethod(
            Invocation.method(#clearPendingSync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  DateTime? getLastSyncTime(String? entityType) =>
      (super.noSuchMethod(Invocation.method(#getLastSyncTime, [entityType]))
          as DateTime?);

  @override
  _i4.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i7.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<Object?> get tasksCollection =>
      (super.noSuchMethod(
            Invocation.getter(#tasksCollection),
            returnValue: _FakeCollectionReference_0<Object?>(
              this,
              Invocation.getter(#tasksCollection),
            ),
          )
          as _i2.CollectionReference<Object?>);

  @override
  _i2.CollectionReference<Object?> get subjectsCollection =>
      (super.noSuchMethod(
            Invocation.getter(#subjectsCollection),
            returnValue: _FakeCollectionReference_0<Object?>(
              this,
              Invocation.getter(#subjectsCollection),
            ),
          )
          as _i2.CollectionReference<Object?>);

  @override
  _i4.Future<_i8.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.CollectionReference<Object?> sharedTasksCollection(String? careerId) =>
      (super.noSuchMethod(
            Invocation.method(#sharedTasksCollection, [careerId]),
            returnValue: _FakeCollectionReference_0<Object?>(
              this,
              Invocation.method(#sharedTasksCollection, [careerId]),
            ),
          )
          as _i2.CollectionReference<Object?>);

  @override
  _i4.Future<String> addTask(_i5.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(this, Invocation.method(#addTask, [task])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateTask(_i5.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId, {String? careerId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId], {#careerId: careerId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Task>> getTasks({String? careerId}) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {#careerId: careerId}),
            returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i4.Future<List<_i5.Task>>);

  @override
  List<_i5.Task> applyCurrentUserProgress(List<_i5.Task>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#applyCurrentUserProgress, [tasks]),
            returnValue: <_i5.Task>[],
          )
          as List<_i5.Task>);

  @override
  List<_i5.Task> getTasksFromCache() =>
      (super.noSuchMethod(
            Invocation.method(#getTasksFromCache, []),
            returnValue: <_i5.Task>[],
          )
          as List<_i5.Task>);

  @override
  _i4.Future<List<_i5.Task>> getPendingTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingTasks, []),
            returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<List<_i5.Task>> getOverdueTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, []),
            returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<List<_i5.Task>> getDeliveredTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getDeliveredTasks, []),
            returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<void> updateTaskStatus(
    String? taskId,
    bool? isCompleted,
    bool? isSubmitted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [
              taskId,
              isCompleted,
              isSubmitted,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleTaskCompletion(_i5.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTaskCompletion, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> addSubject(_i6.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#addSubject, [subject]),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#addSubject, [subject]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateSubject(_i6.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [subject]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSubject(String? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [subjectId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Subject>> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue: _i4.Future<List<_i6.Subject>>.value(<_i6.Subject>[]),
          )
          as _i4.Future<List<_i6.Subject>>);

  @override
  List<_i6.Subject> getSubjectsFromCache() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectsFromCache, []),
            returnValue: <_i6.Subject>[],
          )
          as List<_i6.Subject>);

  @override
  _i4.Future<List<_i6.Subject>> getPublicSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getPublicSubjects, []),
            returnValue: _i4.Future<List<_i6.Subject>>.value(<_i6.Subject>[]),
          )
          as _i4.Future<List<_i6.Subject>>);
}
