// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA2q3b2wjMSFHh7hWfZcv5-SERpuLmsGA',
    appId: '1:651071616802:web:92aaf37bb790083d2b177b',
    messagingSenderId: '651071616802',
    projectId: 'bitacora-2d643',
    authDomain: 'bitacora-2d643.firebaseapp.com',
    storageBucket: 'bitacora-2d643.firebasestorage.app',
    measurementId: 'G-WGLWXDTHD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkEeyGhg8e5dkP5VKfQks58c-EEUQwGl8',
    appId: '1:651071616802:android:ed6cf25b1ae2cb5f2b177b',
    messagingSenderId: '651071616802',
    projectId: 'bitacora-2d643',
    authDomain: 'bitacora-2d643.firebaseapp.com',
    storageBucket: 'bitacora-2d643.firebasestorage.app',
  );
}
